version: '3.4'

services:
  snqtradingcompany.webapi:
    image: "snqtradingcompanywebapi"
    container_name: snqtradingcompany.webapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_CONNECTIONSTRING=Data Source=dbserver; Database=SnQTradingCompanyDb; User Id=sa;Password=passme!1234
    ports:
      - "32785:80"
      - "443"
    depends_on:
      - dbserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  snqtradingcompany.aspmvc:
    image: "snqtradingcompanyaspmvc"
    container_name: snqtradingcompany.aspmvc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_CONNECTIONSTRING=Data Source=dbserver; Database=SnQTradingCompanyDb; User Id=sa;Password=passme!1234
    ports:
      - "32790:80"
      - "443"
    depends_on:
      - dbserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  dbserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: "passme!1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "C:\\Share\\Docker\\MSSQL:/var/opt/mssql/data/"